// Code generated by mockery v2.20.0. DO NOT EDIT.

package gw_cache

import mock "github.com/stretchr/testify/mock"

// MockProccessorI is an autogenerated mock type for the ProccessorI type
type MockProccessorI[T interface{}, K interface{}] struct {
	mock.Mock
}

type MockProccessorI_Expecter[T interface{}, K interface{}] struct {
	mock *mock.Mock
}

func (_m *MockProccessorI[T, K]) EXPECT() *MockProccessorI_Expecter[T, K] {
	return &MockProccessorI_Expecter[T, K]{mock: &_m.Mock}
}

// CallUServices provides a mock function with given fields: _a0
func (_m *MockProccessorI[T, K]) CallUServices(_a0 T) (K, *RequestError) {
	ret := _m.Called(_a0)

	var r0 K
	var r1 *RequestError
	if rf, ok := ret.Get(0).(func(T) (K, *RequestError)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(T) K); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(K)
	}

	if rf, ok := ret.Get(1).(func(T) *RequestError); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*RequestError)
		}
	}

	return r0, r1
}

// MockProccessorI_CallUServices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CallUServices'
type MockProccessorI_CallUServices_Call[T interface{}, K interface{}] struct {
	*mock.Call
}

// CallUServices is a helper method to define mock.On call
//   - _a0 T
func (_e *MockProccessorI_Expecter[T, K]) CallUServices(_a0 interface{}) *MockProccessorI_CallUServices_Call[T, K] {
	return &MockProccessorI_CallUServices_Call[T, K]{Call: _e.mock.On("CallUServices", _a0)}
}

func (_c *MockProccessorI_CallUServices_Call[T, K]) Run(run func(_a0 T)) *MockProccessorI_CallUServices_Call[T, K] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(T))
	})
	return _c
}

func (_c *MockProccessorI_CallUServices_Call[T, K]) Return(_a0 K, _a1 *RequestError) *MockProccessorI_CallUServices_Call[T, K] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProccessorI_CallUServices_Call[T, K]) RunAndReturn(run func(T) (K, *RequestError)) *MockProccessorI_CallUServices_Call[T, K] {
	_c.Call.Return(run)
	return _c
}

// ToMapKey provides a mock function with given fields: _a0
func (_m *MockProccessorI[T, K]) ToMapKey(_a0 T) (string, error) {
	ret := _m.Called(_a0)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(T) (string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(T) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(T) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProccessorI_ToMapKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToMapKey'
type MockProccessorI_ToMapKey_Call[T interface{}, K interface{}] struct {
	*mock.Call
}

// ToMapKey is a helper method to define mock.On call
//   - _a0 T
func (_e *MockProccessorI_Expecter[T, K]) ToMapKey(_a0 interface{}) *MockProccessorI_ToMapKey_Call[T, K] {
	return &MockProccessorI_ToMapKey_Call[T, K]{Call: _e.mock.On("ToMapKey", _a0)}
}

func (_c *MockProccessorI_ToMapKey_Call[T, K]) Run(run func(_a0 T)) *MockProccessorI_ToMapKey_Call[T, K] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(T))
	})
	return _c
}

func (_c *MockProccessorI_ToMapKey_Call[T, K]) Return(_a0 string, _a1 error) *MockProccessorI_ToMapKey_Call[T, K] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProccessorI_ToMapKey_Call[T, K]) RunAndReturn(run func(T) (string, error)) *MockProccessorI_ToMapKey_Call[T, K] {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockProccessorI interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockProccessorI creates a new instance of MockProccessorI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockProccessorI[T interface{}, K interface{}](t mockConstructorTestingTNewMockProccessorI) *MockProccessorI[T, K] {
	mock := &MockProccessorI[T, K]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
