// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	models "github.com/geniussportsgroup/gateway_cache/models"
	mock "github.com/stretchr/testify/mock"
)

// ProcessorI is an autogenerated mock type for the ProcessorI type
type ProcessorI[T interface{}, K interface{}] struct {
	mock.Mock
}

type ProcessorI_Expecter[T interface{}, K interface{}] struct {
	mock *mock.Mock
}

func (_m *ProcessorI[T, K]) EXPECT() *ProcessorI_Expecter[T, K] {
	return &ProcessorI_Expecter[T, K]{mock: &_m.Mock}
}

// CallUServices provides a mock function with given fields: _a0
func (_m *ProcessorI[T, K]) CallUServices(_a0 T) (K, *models.RequestError) {
	ret := _m.Called(_a0)

	var r0 K
	var r1 *models.RequestError
	if rf, ok := ret.Get(0).(func(T) (K, *models.RequestError)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(T) K); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(K)
	}

	if rf, ok := ret.Get(1).(func(T) *models.RequestError); ok {
		r1 = rf(_a0)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*models.RequestError)
		}
	}

	return r0, r1
}

// ProcessorI_CallUServices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CallUServices'
type ProcessorI_CallUServices_Call[T interface{}, K interface{}] struct {
	*mock.Call
}

// CallUServices is a helper method to define mock.On call
//   - _a0 T
func (_e *ProcessorI_Expecter[T, K]) CallUServices(_a0 interface{}) *ProcessorI_CallUServices_Call[T, K] {
	return &ProcessorI_CallUServices_Call[T, K]{Call: _e.mock.On("CallUServices", _a0)}
}

func (_c *ProcessorI_CallUServices_Call[T, K]) Run(run func(_a0 T)) *ProcessorI_CallUServices_Call[T, K] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(T))
	})
	return _c
}

func (_c *ProcessorI_CallUServices_Call[T, K]) Return(_a0 K, _a1 *models.RequestError) *ProcessorI_CallUServices_Call[T, K] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProcessorI_CallUServices_Call[T, K]) RunAndReturn(run func(T) (K, *models.RequestError)) *ProcessorI_CallUServices_Call[T, K] {
	_c.Call.Return(run)
	return _c
}

// ToMapKey provides a mock function with given fields: _a0
func (_m *ProcessorI[T, K]) ToMapKey(_a0 T) (string, error) {
	ret := _m.Called(_a0)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(T) (string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(T) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(T) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProcessorI_ToMapKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToMapKey'
type ProcessorI_ToMapKey_Call[T interface{}, K interface{}] struct {
	*mock.Call
}

// ToMapKey is a helper method to define mock.On call
//   - _a0 T
func (_e *ProcessorI_Expecter[T, K]) ToMapKey(_a0 interface{}) *ProcessorI_ToMapKey_Call[T, K] {
	return &ProcessorI_ToMapKey_Call[T, K]{Call: _e.mock.On("ToMapKey", _a0)}
}

func (_c *ProcessorI_ToMapKey_Call[T, K]) Run(run func(_a0 T)) *ProcessorI_ToMapKey_Call[T, K] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(T))
	})
	return _c
}

func (_c *ProcessorI_ToMapKey_Call[T, K]) Return(_a0 string, _a1 error) *ProcessorI_ToMapKey_Call[T, K] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProcessorI_ToMapKey_Call[T, K]) RunAndReturn(run func(T) (string, error)) *ProcessorI_ToMapKey_Call[T, K] {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewProcessorI interface {
	mock.TestingT
	Cleanup(func())
}

// NewProcessorI creates a new instance of ProcessorI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewProcessorI[T interface{}, K interface{}](t mockConstructorTestingTNewProcessorI) *ProcessorI[T, K] {
	mock := &ProcessorI[T, K]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
